# Generated by Django 3.1 on 2020-08-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_tumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tumb',
            new_name='thumb',
        ),
    ]
