# Generated by Django 3.1 on 2020-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filePath',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, path=None),
        ),
    ]
