# Generated by Django 3.1 on 2020-08-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200819_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='filePath',
        ),
    ]
